use_frameworks!

# 远程私有仓库 xxooSpecs
source 'http://192.168.1.119/xxoogo_livechat/xxoospecs.git'

# 远程公有仓库
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'XOChatModule_Example' do
  pod 'XOChatModule', :path => '../'
  pod 'TZImagePickerController'
  
  target 'XOChatModule_Tests' do
    inherit! :search_paths
    
    
  end
end
